export const Colors = {
  light: {
    uiBackground: "#fff",
    navBackground: "#eee",
    title: "#000",
    text: "#333",
    subtext: "#aaa",
    inactiveIcon: "gray",
    underline: "#000",
    cardBackground: "#f6f6f6",
    checkBox: "#000",
    address: "#fff",
    size: "#ddd",
    placeholder: "#777",
    iconColor: "#686477",
    iconColorFocused: "#201e2b",
  },
  dark: {
    uiBackground: "#000",
    navBackground: "#111",
    title: "#fff",
    text: "#ddd",
    subtext: "#aaa",
    inactiveIcon: "#bbb",
    underline: "#fff",
    cardBackground: "#1f1f1f",
    checkBox: "#ddd",
    address: "#1f1f1f",
    size: "#fff",
    placeholder: "#bbbb",
    iconColor: "#9591a5",
    iconColorFocused: "#fff",
  },
};
